import { VenueType } from "@prisma/client";
import type { VenueCapability, VenueCatalog, VenueMarketMode, VenueOption } from "@/lib/venue-capabilities";

const NETWORK_OPTIONS: VenueOption[] = [
  { value: "testnet", label: "Testnet" },
  { value: "mainnet", label: "Mainnet" },
];

const CATALOG: Record<VenueType, VenueCapability> = {
  HYPERLIQUID: {
    type: "HYPERLIQUID",
    registryName: "hyperliquid",
    label: "Hyperliquid · Crypto Perps",
    shortLabel: "Hyperliquid",
    description: "DEX perpetual futures with API-wallet auth.",
    assetClass: "crypto",
    assetLabel: "Crypto Perpetuals",
    supportsPaper: true,
    supportsLive: true,
    supportsBacktest: true,
    marketDataMode: "polling",
    markets: [{ value: "futures", label: "Futures" }],
    defaultMarket: "futures",
    symbols: {
      placeholder: "BTC",
      acceptsManualEntry: true,
      formatHint: "Base asset ticker",
      examples: ["BTC", "ETH", "SOL"],
      defaultSymbols: ["BTC", "ETH", "SOL", "ARB", "AVAX", "DOGE"],
    },
    orderFeatures: {
      marketOrders: true,
      limitOrders: false,
      supportsLeverage: true,
      supportsShorting: true,
      supportsCloseAll: true,
    },
    auth: {
      apiKey: {
        enabled: true,
        label: "Private Key (API wallet)",
        placeholder: "0x... (Hyperliquid API wallet key)",
        secret: true,
      },
      apiSecret: { enabled: false },
      apiPassphrase: { enabled: false },
      accountId: { enabled: false },
      ccxtExchangeId: { enabled: false },
      network: { enabled: true, label: "Network", options: NETWORK_OPTIONS },
      metaApiToken: { enabled: false },
      metaApiAccountId: { enabled: false },
    },
  },
  BINANCE: {
    type: "BINANCE",
    registryName: "binance",
    label: "Binance · Crypto",
    shortLabel: "Binance",
    description: "Spot and futures trading on Binance.",
    assetClass: "crypto",
    assetLabel: "Crypto",
    supportsPaper: true,
    supportsLive: true,
    supportsBacktest: true,
    marketDataMode: "stream",
    markets: [
      { value: "spot", label: "Spot" },
      { value: "futures", label: "Futures" },
    ],
    defaultMarket: "spot",
    symbols: {
      placeholder: "BTC/USDT",
      acceptsManualEntry: true,
      formatHint: "BASE/QUOTE",
      examples: ["BTC/USDT", "ETH/USDT", "SOL/USDT"],
      defaultSymbols: ["BTC/USDT", "ETH/USDT", "SOL/USDT", "BNB/USDT", "XRP/USDT"],
    },
    orderFeatures: {
      marketOrders: true,
      limitOrders: false,
      supportsLeverage: true,
      supportsShorting: true,
      supportsCloseAll: true,
    },
    auth: {
      apiKey: { enabled: true, label: "API Key", placeholder: "API key", secret: true },
      apiSecret: { enabled: true, label: "API Secret", placeholder: "API secret", secret: true },
      apiPassphrase: { enabled: false },
      accountId: { enabled: false },
      ccxtExchangeId: { enabled: false },
      network: { enabled: false },
      metaApiToken: { enabled: false },
      metaApiAccountId: { enabled: false },
    },
  },
  BYBIT: {
    type: "BYBIT",
    registryName: "bybit",
    label: "Bybit · Crypto",
    shortLabel: "Bybit",
    description: "Crypto derivatives and spot through the CCXT adapter.",
    assetClass: "crypto",
    assetLabel: "Crypto",
    supportsPaper: true,
    supportsLive: true,
    supportsBacktest: true,
    marketDataMode: "polling",
    markets: [
      { value: "futures", label: "Futures" },
      { value: "spot", label: "Spot" },
    ],
    defaultMarket: "futures",
    symbols: {
      placeholder: "BTC/USDT",
      acceptsManualEntry: true,
      formatHint: "BASE/QUOTE",
      examples: ["BTC/USDT", "ETH/USDT", "SOL/USDT"],
      defaultSymbols: ["BTC/USDT", "ETH/USDT", "SOL/USDT", "AVAX/USDT"],
    },
    orderFeatures: {
      marketOrders: true,
      limitOrders: false,
      supportsLeverage: true,
      supportsShorting: true,
      supportsCloseAll: true,
    },
    auth: {
      apiKey: { enabled: true, label: "API Key", placeholder: "API key", secret: true },
      apiSecret: { enabled: true, label: "API Secret", placeholder: "API secret", secret: true },
      apiPassphrase: { enabled: false },
      accountId: { enabled: false },
      ccxtExchangeId: { enabled: false },
      network: { enabled: false },
      metaApiToken: { enabled: false },
      metaApiAccountId: { enabled: false },
    },
  },
  OKX: {
    type: "OKX",
    registryName: "okx",
    label: "OKX · Crypto",
    shortLabel: "OKX",
    description: "OKX spot and derivatives via CCXT.",
    assetClass: "crypto",
    assetLabel: "Crypto",
    supportsPaper: true,
    supportsLive: true,
    supportsBacktest: true,
    marketDataMode: "polling",
    markets: [
      { value: "spot", label: "Spot" },
      { value: "futures", label: "Futures" },
    ],
    defaultMarket: "spot",
    symbols: {
      placeholder: "BTC-USDT",
      acceptsManualEntry: true,
      formatHint: "BASE-QUOTE",
      examples: ["BTC-USDT", "ETH-USDT", "SOL-USDT"],
      defaultSymbols: ["BTC-USDT", "ETH-USDT", "SOL-USDT"],
    },
    orderFeatures: {
      marketOrders: true,
      limitOrders: false,
      supportsLeverage: true,
      supportsShorting: true,
      supportsCloseAll: true,
    },
    auth: {
      apiKey: { enabled: true, label: "API Key", placeholder: "API key", secret: true },
      apiSecret: { enabled: true, label: "API Secret", placeholder: "API secret", secret: true },
      apiPassphrase: { enabled: true, label: "Passphrase", placeholder: "Exchange passphrase", secret: true },
      accountId: { enabled: false },
      ccxtExchangeId: { enabled: false },
      network: { enabled: false },
      metaApiToken: { enabled: false },
      metaApiAccountId: { enabled: false },
    },
  },
  KRAKEN: {
    type: "KRAKEN",
    registryName: "kraken",
    label: "Kraken · Crypto Spot",
    shortLabel: "Kraken",
    description: "Kraken spot trading via CCXT.",
    assetClass: "crypto",
    assetLabel: "Crypto Spot",
    supportsPaper: true,
    supportsLive: true,
    supportsBacktest: true,
    marketDataMode: "polling",
    markets: [{ value: "spot", label: "Spot" }],
    defaultMarket: "spot",
    symbols: {
      placeholder: "BTC/USD",
      acceptsManualEntry: true,
      formatHint: "BASE/QUOTE",
      examples: ["BTC/USD", "ETH/USD", "SOL/USD"],
      defaultSymbols: ["BTC/USD", "ETH/USD", "SOL/USD"],
    },
    orderFeatures: {
      marketOrders: true,
      limitOrders: false,
      supportsLeverage: false,
      supportsShorting: false,
      supportsCloseAll: true,
    },
    auth: {
      apiKey: { enabled: true, label: "API Key", placeholder: "API key", secret: true },
      apiSecret: { enabled: true, label: "API Secret", placeholder: "API secret", secret: true },
      apiPassphrase: { enabled: false },
      accountId: { enabled: false },
      ccxtExchangeId: { enabled: false },
      network: { enabled: false },
      metaApiToken: { enabled: false },
      metaApiAccountId: { enabled: false },
    },
  },
  COINBASE: {
    type: "COINBASE",
    registryName: "coinbase",
    label: "Coinbase Advanced · Crypto Spot",
    shortLabel: "Coinbase",
    description: "Coinbase spot trading.",
    assetClass: "crypto",
    assetLabel: "Crypto Spot",
    supportsPaper: true,
    supportsLive: true,
    supportsBacktest: true,
    marketDataMode: "polling",
    markets: [{ value: "spot", label: "Spot" }],
    defaultMarket: "spot",
    symbols: {
      placeholder: "BTC-USD",
      acceptsManualEntry: true,
      formatHint: "BASE-QUOTE",
      examples: ["BTC-USD", "ETH-USD", "SOL-USD"],
      defaultSymbols: ["BTC-USD", "ETH-USD", "SOL-USD"],
    },
    orderFeatures: {
      marketOrders: true,
      limitOrders: false,
      supportsLeverage: false,
      supportsShorting: false,
      supportsCloseAll: true,
    },
    auth: {
      apiKey: { enabled: true, label: "API Key", placeholder: "API key", secret: true },
      apiSecret: { enabled: true, label: "API Secret", placeholder: "API secret", secret: true },
      apiPassphrase: { enabled: true, label: "Passphrase", placeholder: "Exchange passphrase", secret: true },
      accountId: { enabled: false },
      ccxtExchangeId: { enabled: false },
      network: { enabled: false },
      metaApiToken: { enabled: false },
      metaApiAccountId: { enabled: false },
    },
  },
  OANDA: {
    type: "OANDA",
    registryName: "oanda",
    label: "OANDA · Forex / CFDs",
    shortLabel: "OANDA",
    description: "Forex and CFD trading through OANDA.",
    assetClass: "forex",
    assetLabel: "Forex / CFDs",
    supportsPaper: true,
    supportsLive: true,
    supportsBacktest: true,
    marketDataMode: "polling",
    markets: [{ value: "forex", label: "Forex" }],
    defaultMarket: "forex",
    symbols: {
      placeholder: "EUR_USD",
      acceptsManualEntry: true,
      formatHint: "BASE_QUOTE",
      examples: ["EUR_USD", "GBP_USD", "XAU_USD"],
      defaultSymbols: ["EUR_USD", "GBP_USD", "USD_JPY", "XAU_USD"],
    },
    orderFeatures: {
      marketOrders: true,
      limitOrders: false,
      supportsLeverage: true,
      supportsShorting: true,
      supportsCloseAll: true,
    },
    auth: {
      apiKey: { enabled: true, label: "API Key", placeholder: "API key", secret: true },
      apiSecret: { enabled: true, label: "API Secret", placeholder: "API secret", secret: true },
      apiPassphrase: { enabled: false },
      accountId: { enabled: true, label: "Account ID", placeholder: "101-001-12345678-001" },
      ccxtExchangeId: { enabled: false },
      network: { enabled: false },
      metaApiToken: { enabled: false },
      metaApiAccountId: { enabled: false },
    },
  },
  METATRADER: {
    type: "METATRADER",
    registryName: "metatrader",
    label: "MetaTrader · Forex / Metals / Indices",
    shortLabel: "MetaTrader",
    description: "MetaTrader 4/5 through MetaAPI.",
    assetClass: "forex",
    assetLabel: "Forex / Metals / Indices",
    supportsPaper: true,
    supportsLive: true,
    supportsBacktest: true,
    marketDataMode: "polling",
    markets: [{ value: "forex", label: "Forex" }],
    defaultMarket: "forex",
    symbols: {
      placeholder: "EURUSD",
      acceptsManualEntry: true,
      formatHint: "Broker symbol",
      examples: ["EURUSD", "XAUUSD", "US30"],
      defaultSymbols: ["EURUSD", "GBPUSD", "USDJPY", "XAUUSD", "US30"],
    },
    orderFeatures: {
      marketOrders: true,
      limitOrders: false,
      supportsLeverage: true,
      supportsShorting: true,
      supportsCloseAll: true,
    },
    auth: {
      apiKey: { enabled: false },
      apiSecret: { enabled: false },
      apiPassphrase: { enabled: false },
      accountId: { enabled: false },
      ccxtExchangeId: { enabled: false },
      network: { enabled: false },
      metaApiToken: { enabled: true, label: "MetaAPI Token", placeholder: "From metaapi.cloud dashboard", secret: true },
      metaApiAccountId: { enabled: true, label: "MetaAPI Account ID", placeholder: "MT4/MT5 account ID on MetaAPI" },
    },
  },
  ALPACA: {
    type: "ALPACA",
    registryName: "alpaca",
    label: "Alpaca · US Stocks",
    shortLabel: "Alpaca",
    description: "US equities through Alpaca.",
    assetClass: "stocks",
    assetLabel: "Stocks",
    supportsPaper: true,
    supportsLive: true,
    supportsBacktest: true,
    marketDataMode: "polling",
    markets: [{ value: "stocks", label: "Stocks" }],
    defaultMarket: "stocks",
    symbols: {
      placeholder: "AAPL",
      acceptsManualEntry: true,
      formatHint: "Ticker",
      examples: ["AAPL", "TSLA", "NVDA"],
      defaultSymbols: ["AAPL", "TSLA", "NVDA", "MSFT", "SPY"],
    },
    orderFeatures: {
      marketOrders: true,
      limitOrders: false,
      supportsLeverage: false,
      supportsShorting: false,
      supportsCloseAll: true,
    },
    auth: {
      apiKey: { enabled: true, label: "API Key", placeholder: "API key", secret: true },
      apiSecret: { enabled: true, label: "API Secret", placeholder: "API secret", secret: true },
      apiPassphrase: { enabled: false },
      accountId: { enabled: false },
      ccxtExchangeId: { enabled: false },
      network: { enabled: false },
      metaApiToken: { enabled: false },
      metaApiAccountId: { enabled: false },
    },
  },
  IBKR: {
    type: "IBKR",
    registryName: "ibkr",
    label: "Interactive Brokers · Stocks",
    shortLabel: "IBKR",
    description: "Stocks via Interactive Brokers.",
    assetClass: "stocks",
    assetLabel: "Stocks",
    supportsPaper: true,
    supportsLive: true,
    supportsBacktest: true,
    marketDataMode: "polling",
    markets: [{ value: "stocks", label: "Stocks" }],
    defaultMarket: "stocks",
    symbols: {
      placeholder: "AAPL",
      acceptsManualEntry: true,
      formatHint: "Ticker",
      examples: ["AAPL", "TSLA", "NVDA"],
      defaultSymbols: ["AAPL", "TSLA", "NVDA", "MSFT", "QQQ"],
    },
    orderFeatures: {
      marketOrders: true,
      limitOrders: false,
      supportsLeverage: false,
      supportsShorting: false,
      supportsCloseAll: true,
    },
    auth: {
      apiKey: { enabled: true, label: "API Key", placeholder: "API key", secret: true },
      apiSecret: { enabled: true, label: "API Secret", placeholder: "API secret", secret: true },
      apiPassphrase: { enabled: false },
      accountId: { enabled: false },
      ccxtExchangeId: { enabled: false },
      network: { enabled: false },
      metaApiToken: { enabled: false },
      metaApiAccountId: { enabled: false },
    },
  },
  POLYMARKET: {
    type: "POLYMARKET",
    registryName: "polymarket",
    label: "Polymarket · Prediction Markets",
    shortLabel: "Polymarket",
    description: "Prediction-market execution with a dedicated wallet.",
    assetClass: "prediction",
    assetLabel: "Prediction Markets",
    supportsPaper: true,
    supportsLive: true,
    supportsBacktest: false,
    marketDataMode: "polling",
    markets: [{ value: "prediction", label: "Prediction" }],
    defaultMarket: "prediction",
    symbols: {
      placeholder: "Market slug or contract",
      acceptsManualEntry: true,
      formatHint: "Prediction market identifier",
      examples: [],
      defaultSymbols: [],
    },
    orderFeatures: {
      marketOrders: true,
      limitOrders: false,
      supportsLeverage: false,
      supportsShorting: false,
      supportsCloseAll: true,
    },
    auth: {
      apiKey: {
        enabled: true,
        label: "Ethereum Private Key (dedicated trading wallet)",
        placeholder: "0x... — never paste your main wallet's key",
        secret: true,
      },
      apiSecret: { enabled: false },
      apiPassphrase: { enabled: false },
      accountId: { enabled: false },
      ccxtExchangeId: { enabled: false },
      network: { enabled: false },
      metaApiToken: { enabled: false },
      metaApiAccountId: { enabled: false },
    },
  },
  CCXT: {
    type: "CCXT",
    registryName: "ccxt",
    label: "CCXT · Generic Exchange",
    shortLabel: "CCXT",
    description: "Bring your own exchange through CCXT.",
    assetClass: "crypto",
    assetLabel: "Crypto",
    supportsPaper: true,
    supportsLive: true,
    supportsBacktest: true,
    marketDataMode: "polling",
    markets: [
      { value: "spot", label: "Spot" },
      { value: "futures", label: "Futures" },
    ],
    defaultMarket: "spot",
    symbols: {
      placeholder: "BTC/USDT",
      acceptsManualEntry: true,
      formatHint: "Exchange-native market symbol",
      examples: ["BTC/USDT", "ETH/USDT"],
      defaultSymbols: ["BTC/USDT", "ETH/USDT"],
    },
    orderFeatures: {
      marketOrders: true,
      limitOrders: false,
      supportsLeverage: true,
      supportsShorting: true,
      supportsCloseAll: true,
    },
    auth: {
      apiKey: { enabled: true, label: "API Key", placeholder: "API key", secret: true },
      apiSecret: { enabled: true, label: "API Secret", placeholder: "API secret", secret: true },
      apiPassphrase: { enabled: true, label: "Passphrase (optional)", placeholder: "Only for Coinbase, OKX, etc.", secret: true },
      accountId: { enabled: false },
      ccxtExchangeId: { enabled: true, label: "Exchange ID (CCXT)", placeholder: "e.g. kraken, okx, bybit" },
      network: { enabled: false },
      metaApiToken: { enabled: false },
      metaApiAccountId: { enabled: false },
    },
  },
};

export function listVenueCapabilities(): VenueCapability[] {
  return Object.values(CATALOG);
}

export function getVenueCatalog(): VenueCatalog {
  return Object.fromEntries(Object.entries(CATALOG).map(([key, value]) => [key, { ...value }])) as VenueCatalog;
}

export function getVenueCapability(type: string | null | undefined): VenueCapability {
  return CATALOG[(type ?? "BINANCE") as VenueType] ?? CATALOG.BINANCE;
}

export function normalizeVenueMarket(type: string | null | undefined, market: string | null | undefined): VenueMarketMode {
  const capability = getVenueCapability(type);
  const requested = String(market ?? "").toLowerCase();
  const allowed = new Set(capability.markets.map((option) => option.value));
  return allowed.has(requested as VenueMarketMode)
    ? (requested as VenueMarketMode)
    : capability.defaultMarket;
}
