// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/audit" | "/backtest" | "/billing" | "/calendar" | "/copy-trading" | "/dashboard" | "/docs" | "/journal" | "/leaderboard" | "/marketplace" | "/marketplace/[id]" | "/onboarding" | "/rag-memory" | "/settings" | "/sign-in/[[...sign-in]]" | "/sign-up/[[...sign-up]]" | "/terms" | "/trust"
type AppRouteHandlerRoutes = "/api/admin/stats" | "/api/admin/users" | "/api/admin/users/[id]" | "/api/agent/[...path]" | "/api/audit" | "/api/auth/refresh" | "/api/auth/signout" | "/api/backtest/run" | "/api/billing" | "/api/chart" | "/api/copy" | "/api/email/agent-stopped" | "/api/email/weekly-report" | "/api/equity" | "/api/health" | "/api/leaderboard/benchmarks" | "/api/marketplace" | "/api/marketplace/[id]" | "/api/price" | "/api/rag-memory" | "/api/strategies" | "/api/trades" | "/api/user/settings" | "/api/venues" | "/api/venues/[id]" | "/api/venues/[id]/risk" | "/api/venues/[id]/test" | "/api/webhooks/clerk" | "/api/webhooks/payment" | "/api/webhooks/stripe" | "/api/webhooks/tradingview"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/api/admin/stats": {}
  "/api/admin/users": {}
  "/api/admin/users/[id]": { "id": string; }
  "/api/agent/[...path]": { "path": string[]; }
  "/api/audit": {}
  "/api/auth/refresh": {}
  "/api/auth/signout": {}
  "/api/backtest/run": {}
  "/api/billing": {}
  "/api/chart": {}
  "/api/copy": {}
  "/api/email/agent-stopped": {}
  "/api/email/weekly-report": {}
  "/api/equity": {}
  "/api/health": {}
  "/api/leaderboard/benchmarks": {}
  "/api/marketplace": {}
  "/api/marketplace/[id]": { "id": string; }
  "/api/price": {}
  "/api/rag-memory": {}
  "/api/strategies": {}
  "/api/trades": {}
  "/api/user/settings": {}
  "/api/venues": {}
  "/api/venues/[id]": { "id": string; }
  "/api/venues/[id]/risk": { "id": string; }
  "/api/venues/[id]/test": { "id": string; }
  "/api/webhooks/clerk": {}
  "/api/webhooks/payment": {}
  "/api/webhooks/stripe": {}
  "/api/webhooks/tradingview": {}
  "/audit": {}
  "/backtest": {}
  "/billing": {}
  "/calendar": {}
  "/copy-trading": {}
  "/dashboard": {}
  "/docs": {}
  "/journal": {}
  "/leaderboard": {}
  "/marketplace": {}
  "/marketplace/[id]": { "id": string; }
  "/onboarding": {}
  "/rag-memory": {}
  "/settings": {}
  "/sign-in/[[...sign-in]]": { "sign-in"?: string[]; }
  "/sign-up/[[...sign-up]]": { "sign-up"?: string[]; }
  "/terms": {}
  "/trust": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
